Add sleeping until test.pypi upload has happened

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -88,10 +88,21 @@ jobs:
         pushd PyAutoBuild
         python3 release.py --mode=test --minor-version=${{ github.event.inputs.minor_version }}
         popd
+    - name: Wait for packages to upload to Pypi
+      run: |
+        python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple autogalaxy==$VERSION
+        test_condition=$?
+        cnt=0
+        while [[ $test_condition != "0" ]]; do
+          echo "Failed to find package, retrying in 10 seconds.."
+          sleep 10
+          ((cnt=cnt+1))
+          [[ $cnt == "100" ]] && echo "Timed out, tried 100 times" && break
+          python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple autogalaxy==$VERSION
+          test_condition=$?
+        done
     - name: Install all packages
       run: |
-        echo "Waiting for packages to upload to test.pypi..."
-        sleep 60  # Warning, this may not be long enough...
         export DATE_FORMATTED=`date +"%Y.%-m.%-d"`
         export VERSION="${DATE_FORMATTED}.${{ github.event.inputs.minor_version }}"
         python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple autoconf==$VERSION
