Add all packages to wait test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -97,26 +97,21 @@ jobs:
     - name: Wait for packages to upload to Pypi
       shell: bash {0}   # So that we do not exit if a command gives a bad exit code
       run: |
+        export PACKAGES=("autoconf" "autoarray" "autofit" "autogalaxy" "autolens")
         export VERSION="${{ steps.version_number.outputs.version-number }}"
-        python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple autogalaxy==$VERSION
-        test_condition=$?
-        cnt=0
-        while [[ $test_condition != "0" ]]; do
-          echo "Failed to find package, retrying in 10 seconds.."
-          sleep 10
-          ((cnt=cnt+1))
-          [[ $cnt == "100" ]] && echo "Timed out, tried 100 times" && break
-          python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple autogalaxy==$VERSION
+        for project in ${PROJECTS[@]}; do
+          python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple $PACKAGE==$VERSION
           test_condition=$?
+          cnt=0
+          while [[ $test_condition != "0" ]]; do
+            echo "Failed to find package, retrying in 10 seconds.."
+            sleep 10
+            ((cnt=cnt+1))
+            [[ $cnt == "100" ]] && echo "Timed out, tried 100 times" && break
+            python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple $PACKAGE==$VERSION
+            test_condition=$?
+          done
         done
-    - name: Install all packages
-      run: |
-        export VERSION="${{ steps.version_number.outputs.version-number }}"
-        python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple autoconf==$VERSION
-        python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple autoarray==$VERSION
-        python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple autofit==$VERSION
-        python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple autogalaxy==$VERSION
-        python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple autolens==$VERSION
     - name: Pip freeze
       run: |
         python3 -m pip freeze
