wait for packages then pytest

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -70,6 +70,32 @@ jobs:
             pushd "${{ matrix.project.path }}"
             python3 -m twine upload --repository testpypi dist/*
             popd
+        - name: Wait for packages to upload to Pypi
+          shell: bash {0}   # So that we do not exit if a command gives a bad exit code
+          run: |
+            export PACKAGES=("autoconf" "autoarray" "autofit" "autogalaxy" "autolens")
+            export VERSION="${{ steps.version_number.outputs.version-number }}"
+            for PACKAGE in ${PACKAGES[@]}; do
+              python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple $PACKAGE==$VERSION
+              test_condition=$?
+              cnt=0
+              while [[ $test_condition != "0" ]]; do
+                echo "Failed to find package, retrying in 10 seconds.."
+                sleep 10
+                ((cnt=cnt+1))
+                [[ $cnt == "100" ]] && echo "Timed out, tried 100 times" && break
+                python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple $PACKAGE==$VERSION
+                test_condition=$?
+              done
+            done
+          - name: Run unittests
+            run: |
+              pushd "${{ matrix.project.path }}"
+              if test -f "optional_requirements.txt"
+              then
+                pip install -r optional_requirements.txt
+              fi
+              python3 -m pytest
 
 #
 #   release:
