wait for package to be available

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -128,7 +128,16 @@ jobs:
         python-version: ${{ matrix.python-version }}
     - name: Install AutoLens
       run: |
-        python3 -m pip install "autolens==${{ needs.release_test_pypi.outputs.version_number }}"
+        test_condition=$?
+        cnt=0
+        while [[ $test_condition != "0" ]]; do
+          echo "Failed to find package, retrying in 10 seconds.."
+          sleep 10
+          ((cnt=cnt+1))
+          [[ $cnt == "100" ]] && echo "Timed out, tried 100 times" && break
+          python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple "autolens==${{ needs.release_test_pypi.outputs.version_number }}"
+          test_condition=$?
+        done
     - name: Run Python scripts Autolens
       run: |
         echo $PYTHONPATH
