reverted to include all steps

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,208 +10,208 @@ on:
   push:
 
 jobs:
-#   version_number:
-#     runs-on: ubuntu-latest
-#     outputs:
-#       version_number: ${{ steps.version_number.outputs.version_number }}
-#     steps:
-#       - name: Compute version number
-#         run: |
-#           export DATE_FORMATTED=`date +"%Y.%-m.%-d"`
-#           MINOR_VERSION="${{ github.event.inputs.minor_version }}"
-#           VERSION="${DATE_FORMATTED}.${MINOR_VERSION:-${{ github.run_number }}}"
-#           RUN_ATTEMPT="${{ github.run_attempt }}"
-#           if [ "$RUN_ATTEMPT" -gt "1" ]
-#           then
-#               VERSION="$VERSION.$RUN_ATTEMPT"
-#           fi
-#           export VERSION
-#           echo "::set-output name=version_number::${VERSION}"
-#         id: version_number
-#
-#   release_test_pypi:
-#         runs-on: ubuntu-latest
-#         needs: version_number
-#         env:
-#           TWINE_REPOSITORY: testpypi
-#           TWINE_USERNAME: __token__
-#           TWINE_PASSWORD: ${{ secrets.TEST_PYPI }}
-#         strategy:
-#           matrix:
-#             python-version: [3.8]  # 3.9 not supported on numba as of 2020-02-11
-#             project:
-#               - repository: rhayes777/PyAutoConf
-#                 ref: master
-#                 path: PyAutoConf
-#               - repository: rhayes777/PyAutoFit
-#                 ref: master
-#                 path: PyAutoFit
-#               - repository: Jammy2211/PyAutoArray
-#                 ref: master
-#                 path: PyAutoArray
-#               - repository: Jammy2211/PyAutoGalaxy
-#                 ref: master
-#                 path: PyAutoGalaxy
-#               - repository: Jammy2211/PyAutoLens
-#                 ref: master
-#                 path: PyAutoLens
-#         steps:
-#         - uses: actions/checkout@v2
-#           with:
-#               path: PyAutoBuild
-#         - name: Checkout
-#           uses: actions/checkout@v2
-#           with:
-#             repository: "${{ matrix.project.repository }}"
-#             ref: "${{ matrix.project.ref }}"
-#             path: "${{ matrix.project.path }}"
-#         - name: Set up Python ${{ matrix.python-version }}
-#           uses: actions/setup-python@v2
-#           with:
-#             python-version: ${{ matrix.python-version }}
-#         - name: Build
-#           run: |
-#             pushd "${{ matrix.project.path }}"
-#             export VERSION="${{ needs.version_number.outputs.version_number }}"
-#             sed -i "s/__version__ = [\.\"\'0-9]*/__version__ = \"$VERSION\"/g" */__init__.py
-#             python3 -m pip install --upgrade build
-#             python3 -m build
-#             popd
-#         - name: Upload to test PyPI
-#           run: |
-#             python3 -m pip install twine
-#             pushd "${{ matrix.project.path }}"
-#             python3 -m twine upload --repository testpypi dist/*
-#             popd
-#         - name: Wait for packages to upload to Pypi
-#           shell: bash {0}   # So that we do not exit if a command gives a bad exit code
-#           run: |
-#             export PACKAGES=("autoconf" "autoarray" "autofit" "autogalaxy" "autolens")
-#             export VERSION="${{ needs.version_number.outputs.version_number }}"
-#             for PACKAGE in ${PACKAGES[@]}; do
-#               python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple $PACKAGE==$VERSION
-#               test_condition=$?
-#               cnt=0
-#               while [[ $test_condition != "0" ]]; do
-#                 echo "Failed to find package, retrying in 10 seconds.."
-#                 sleep 10
-#                 ((cnt=cnt+1))
-#                 [[ $cnt == "100" ]] && echo "Timed out, tried 100 times" && break
-#                 python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple $PACKAGE==$VERSION
-#                 test_condition=$?
-#               done
-#             done
-#         - name: Run unittests
-#           run: |
-#             pushd "${{ matrix.project.path }}"
-#             if test -f "optional_requirements.txt"
-#             then
-#               pip install Cython
-#               pip install -r optional_requirements.txt
-#             fi
-#             python3 -m pytest
+  version_number:
+    runs-on: ubuntu-latest
+    outputs:
+      version_number: ${{ steps.version_number.outputs.version_number }}
+    steps:
+      - name: Compute version number
+        run: |
+          export DATE_FORMATTED=`date +"%Y.%-m.%-d"`
+          MINOR_VERSION="${{ github.event.inputs.minor_version }}"
+          VERSION="${DATE_FORMATTED}.${MINOR_VERSION:-${{ github.run_number }}}"
+          RUN_ATTEMPT="${{ github.run_attempt }}"
+          if [ "$RUN_ATTEMPT" -gt "1" ]
+          then
+              VERSION="$VERSION.$RUN_ATTEMPT"
+          fi
+          export VERSION
+          echo "::set-output name=version_number::${VERSION}"
+        id: version_number
 
-#   run_scripts:
-#     runs-on: ubuntu-latest
-#     needs:
-#       - release_test_pypi
-#       - version_number
-#     strategy:
-#       fail-fast: false
-#       matrix:
-#         python-version: [3.8]
-#         project:
-#             - name: autolens
-#               directory: howtolens
-#             - name: autolens
-#               directory: overview
-#             - name: autolens
-#               directory: imaging
-#             - name: autolens
-#               directory: interferometer
-#             - name: autolens
-#               directory: multi
-#             - name: autolens
-#               directory: point_source
-#             - name: autolens
-#               directory: misc
-#             - name: autolens
-#               directory: plot
-#             - name: autolens
-#               directory: results
-#               config_directory: default
-#             - name: autofit
-#               directory: simulators
-#               config_directory: default
-#             - name: autofit
-#               directory: howtofit
-#               config_directory: default
-#             - name: autofit
-#               directory: overview
-#               config_directory: default
-#             - name: autofit
-#               directory: features
-#               config_directory: default
-#             - name: autofit
-#               directory: searches
-#               config_directory: default
-#     steps:
-#     - name: Configure
-#       id: configure
-#       run: |
-#         if [ ${{ matrix.project.name }} == "autolens" ]
-#         then
-#             echo "::set-output name=repository::Jammy2211/PyAutoLens"
-#             echo "::set-output name=path::PyAutoLens"
-#             echo "::set-output name=workspace_repository::Jammy2211/autolens_workspace"
-#             echo "::set-output name=workspace_path::autolens_workspace"
-#         else
-#             echo "::set-output name=repository::rhayes777/PyAutoFit"
-#             echo "::set-output name=path::PyAutoFit"
-#             echo "::set-output name=workspace_repository::Jammy2211/autofit_workspace"
-#             echo "::set-output name=workspace_path::autofit_workspace"
-#         fi
-#         config_directory="${{ matrix.project.config_directory }}"
-#         echo "::set-output name=config_directory::${config_directory:-test}"
-#     - uses: actions/checkout@v2
-#       with:
-#           path: PyAutoBuild
-#     - name: Checkout project
-#       uses: actions/checkout@v2
-#       with:
-#         repository: "${{ steps.configure.outputs.repository }}"
-#         path: "${{ steps.configure.outputs.path }}"
-#     - name: Checkout workspace
-#       uses: actions/checkout@v2
-#       with:
-#         repository: ${{ steps.configure.outputs.workspace_repository }}
-#         ref: master
-#         path: ${{ steps.configure.outputs.workspace_path }}
-#     - name: Set up Python ${{ matrix.python-version }}
-#       uses: actions/setup-python@v2
-#       with:
-#         python-version: ${{ matrix.python-version }}
-#     - name: Install optional requirements
-#       if: test -f "${{ steps.configure.outputs.path }}/optional_requirements.txt"
-#       run: |
-#         echo "Installing optional requirements"
-#         pip install Cython
-#         python3 -m pip install -r "${{ steps.configure.outputs.path }}/optional_requirements.txt"
-#     - name: Install project
-#       run: |
-#         python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple "${{ matrix.project.name }}==${{ needs.version_number.outputs.version_number }}"
-#     - name: Run Python scripts
-#       run: |
-#         pushd PyAutoBuild
-#         cp -r "${{ matrix.project.name }}/configs/${{ steps.configure.outputs.config_directory }}" "../${{ steps.configure.outputs.workspace_path }}/config"
-#         export PYTHONPATH=$PYTHONPATH:../
-#         python3 "${{ matrix.project.name }}/run_python.py" ${{ matrix.project.directory }}
+  release_test_pypi:
+        runs-on: ubuntu-latest
+        needs: version_number
+        env:
+          TWINE_REPOSITORY: testpypi
+          TWINE_USERNAME: __token__
+          TWINE_PASSWORD: ${{ secrets.TEST_PYPI }}
+        strategy:
+          matrix:
+            python-version: [3.8]  # 3.9 not supported on numba as of 2020-02-11
+            project:
+              - repository: rhayes777/PyAutoConf
+                ref: master
+                path: PyAutoConf
+              - repository: rhayes777/PyAutoFit
+                ref: master
+                path: PyAutoFit
+              - repository: Jammy2211/PyAutoArray
+                ref: master
+                path: PyAutoArray
+              - repository: Jammy2211/PyAutoGalaxy
+                ref: master
+                path: PyAutoGalaxy
+              - repository: Jammy2211/PyAutoLens
+                ref: master
+                path: PyAutoLens
+        steps:
+        - uses: actions/checkout@v2
+          with:
+              path: PyAutoBuild
+        - name: Checkout
+          uses: actions/checkout@v2
+          with:
+            repository: "${{ matrix.project.repository }}"
+            ref: "${{ matrix.project.ref }}"
+            path: "${{ matrix.project.path }}"
+        - name: Set up Python ${{ matrix.python-version }}
+          uses: actions/setup-python@v2
+          with:
+            python-version: ${{ matrix.python-version }}
+        - name: Build
+          run: |
+            pushd "${{ matrix.project.path }}"
+            export VERSION="${{ needs.version_number.outputs.version_number }}"
+            sed -i "s/__version__ = [\.\"\'0-9]*/__version__ = \"$VERSION\"/g" */__init__.py
+            python3 -m pip install --upgrade build
+            python3 -m build
+            popd
+        - name: Upload to test PyPI
+          run: |
+            python3 -m pip install twine
+            pushd "${{ matrix.project.path }}"
+            python3 -m twine upload --repository testpypi dist/*
+            popd
+        - name: Wait for packages to upload to Pypi
+          shell: bash {0}   # So that we do not exit if a command gives a bad exit code
+          run: |
+            export PACKAGES=("autoconf" "autoarray" "autofit" "autogalaxy" "autolens")
+            export VERSION="${{ needs.version_number.outputs.version_number }}"
+            for PACKAGE in ${PACKAGES[@]}; do
+              python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple $PACKAGE==$VERSION
+              test_condition=$?
+              cnt=0
+              while [[ $test_condition != "0" ]]; do
+                echo "Failed to find package, retrying in 10 seconds.."
+                sleep 10
+                ((cnt=cnt+1))
+                [[ $cnt == "100" ]] && echo "Timed out, tried 100 times" && break
+                python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple $PACKAGE==$VERSION
+                test_condition=$?
+              done
+            done
+        - name: Run unittests
+          run: |
+            pushd "${{ matrix.project.path }}"
+            if test -f "optional_requirements.txt"
+            then
+              pip install Cython
+              pip install -r optional_requirements.txt
+            fi
+            python3 -m pytest
+
+  run_scripts:
+    runs-on: ubuntu-latest
+    needs:
+      - release_test_pypi
+      - version_number
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version: [3.8]
+        project:
+            - name: autolens
+              directory: howtolens
+            - name: autolens
+              directory: overview
+            - name: autolens
+              directory: imaging
+            - name: autolens
+              directory: interferometer
+            - name: autolens
+              directory: multi
+            - name: autolens
+              directory: point_source
+            - name: autolens
+              directory: misc
+            - name: autolens
+              directory: plot
+            - name: autolens
+              directory: results
+              config_directory: default
+            - name: autofit
+              directory: simulators
+              config_directory: default
+            - name: autofit
+              directory: howtofit
+              config_directory: default
+            - name: autofit
+              directory: overview
+              config_directory: default
+            - name: autofit
+              directory: features
+              config_directory: default
+            - name: autofit
+              directory: searches
+              config_directory: default
+    steps:
+    - name: Configure
+      id: configure
+      run: |
+        if [ ${{ matrix.project.name }} == "autolens" ]
+        then
+            echo "::set-output name=repository::Jammy2211/PyAutoLens"
+            echo "::set-output name=path::PyAutoLens"
+            echo "::set-output name=workspace_repository::Jammy2211/autolens_workspace"
+            echo "::set-output name=workspace_path::autolens_workspace"
+        else
+            echo "::set-output name=repository::rhayes777/PyAutoFit"
+            echo "::set-output name=path::PyAutoFit"
+            echo "::set-output name=workspace_repository::Jammy2211/autofit_workspace"
+            echo "::set-output name=workspace_path::autofit_workspace"
+        fi
+        config_directory="${{ matrix.project.config_directory }}"
+        echo "::set-output name=config_directory::${config_directory:-test}"
+    - uses: actions/checkout@v2
+      with:
+          path: PyAutoBuild
+    - name: Checkout project
+      uses: actions/checkout@v2
+      with:
+        repository: "${{ steps.configure.outputs.repository }}"
+        path: "${{ steps.configure.outputs.path }}"
+    - name: Checkout workspace
+      uses: actions/checkout@v2
+      with:
+        repository: ${{ steps.configure.outputs.workspace_repository }}
+        ref: master
+        path: ${{ steps.configure.outputs.workspace_path }}
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: Install optional requirements
+      if: test -f "${{ steps.configure.outputs.path }}/optional_requirements.txt"
+      run: |
+        echo "Installing optional requirements"
+        pip install Cython
+        python3 -m pip install -r "${{ steps.configure.outputs.path }}/optional_requirements.txt"
+    - name: Install project
+      run: |
+        python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple "${{ matrix.project.name }}==${{ needs.version_number.outputs.version_number }}"
+    - name: Run Python scripts
+      run: |
+        pushd PyAutoBuild
+        cp -r "${{ matrix.project.name }}/configs/${{ steps.configure.outputs.config_directory }}" "../${{ steps.configure.outputs.workspace_path }}/config"
+        export PYTHONPATH=$PYTHONPATH:../
+        python3 "${{ matrix.project.name }}/run_python.py" ${{ matrix.project.directory }}
 
   run_notebooks:
     runs-on: ubuntu-latest
-#     needs:
-#       - release_test_pypi
-#       - version_number
+    needs:
+      - release_test_pypi
+      - version_number
     strategy:
       fail-fast: false
       matrix:
@@ -299,7 +299,7 @@ jobs:
         python3 -m pip install -r "${{ steps.configure.outputs.path }}/optional_requirements.txt"
     - name: Install project
       run: |
-        python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple "${{ matrix.project.name }}==2022.9.23.128"
+        python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple "${{ matrix.project.name }}==${{ needs.version_number.outputs.version_number }}"
     - name: Install Jupyter dependency
       run: |
         pip install jupyter ipynb-py-convert
